name: Release package workflow

on:
  release:
    types: [created] 
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/swamikalagiri
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm ci
      - run: npm login --registry=https://npm.pkg.github.com
      - run: npm publish
       # env:
       #  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
